### ISSUE TITLE
Issue building the dev client after installing this package

### ISSUE THREAD

**Issue by zameel7** [sAleksovski/react-native-android-widget#91] opened 2024-06-09 07:16 UTC
I am trying to create a widget for my app. I am going with the tutorial [here](https://saleksovski.github.io/react-native-android-widget/docs/tutorial/widget-design). Once I installed the package and rebuild the dev client I get an error.

<img width="1082" alt="Screenshot 2024-06-09 at 12 44 09 PM" src="https://github.com/sAleksovski/react-native-android-widget/assets/43750093/bf08362f-3e5b-4500-b810-4f4620cbf7e9">

**Comment by sAleksovski** [comment] 2024-06-09 07:38
Your widget config should contain a widgets array. See https://saleksovski.github.io/react-native-android-widget/docs/tutorial/register-widget-expo#use-config-plugin-in-appjsonconfigjsconfigts

**Comment by zameel7** [comment] 2024-06-10 01:57
@sAleksovski , in that we have to give a preview screenshot too right? So, for that, shouldn't I get the preview first?

**Comment by sAleksovski** [comment] 2024-06-10 05:56
The preview image is optional, you can use it without image, get the preview, the set it.

**Comment by sAleksovski** [comment] 2024-06-10 21:34
Closing since this is not a bug with the library, but a configuration issue in the app config.

**Closed by sAleksovski** 2024-06-10 21:34 UTC
