### ISSUE TITLE
ListWidget does not scroll on single finger swipe

### ISSUE THREAD

**Issue by nscerrimt** [sAleksovski/react-native-android-widget#49] opened 2023-11-18 14:40 UTC
I have managed to use the ListDemoWidget in my project.  When previewing the screen, the scroll works fine.  However, when using the actual widget on device, swiping the list with a single finger does not make the list scroll.  To manage to scroll, I need to use two separate fingers when swiping on the widget.

ADB Log on swipe: 
`11-18 15:54:00.611  4386  4386 W View    : requestLayout() improperly called by android.widget.LinearLayout{b492d34 VFE...C.. ......ID 0,3-936,105 #7f0a00a2 app:id/animated_hint_layout viewInfo = } during layout: running second layout pass`

**OS:** Android 13
**Device:** One Plus 
Expo App

https://github.com/sAleksovski/react-native-android-widget/assets/58111250/829ccdc4-10aa-417e-9831-b5a733783477

**Comment by sAleksovski** [comment] 2023-11-19 08:25
I could not reproduce this.

Looks like you need the two-finger swipe to start the scrolling, after that single finger scrolling is working.

From the video it looks like the launcher is intercepting the scroll and trying to open the app drawer.

Can you try the Gmail widget (or any other widget that has a scroll) to see if it works correctly?

**Comment by sAleksovski** [comment] 2023-11-29 18:26
Did you try with some other widget that has scrolling?

**Comment by sAleksovski** [comment] 2024-01-04 21:14
Closing this since I could not reproduce, and there was no additional info.

**Closed by sAleksovski** 2024-01-04 21:14 UTC
