### ISSUE TITLE
setBorderColor in class CSSBackgroundDrawable not working with given types

### ISSUE THREAD

**Issue by amrita058** [sAleksovski/react-native-android-widget#105] opened 2024-11-27 10:39 UTC
i tried implementing the example in this repo and got the following error:

  method setBorderColor in class CSSBackgroundDrawable cannot be applied to given types;  

  getReactViewBackground().setBorderColor(
                     ^
  required: int,Integer
  found:    int,int,int
  reason: actual and formal argument lists differ in length

**Comment by jolindroth** [comment] 2024-11-28 08:15
Duplicate of #106

**Comment by sAleksovski** [comment] 2024-11-28 20:17
This looks like an issue with React Native 0.76.
I just released 0.15.1 that works with 0.76 (but not older React Native versions).

The only caveat is that it currently does not work with new architecture.

**Closed by sAleksovski** 2024-11-28 20:17 UTC
