### ISSUE TITLE
DebugEventsWidgets does not log the automatic UPDATE event (updatePeriodMillis) after more than 40 min

### ISSUE THREAD

**Issue by Facundo1609** [sAleksovski/react-native-android-widget#47] opened 2023-11-14 18:41 UTC
Hey! I'm testing this amazing library, is really useful!! Congrats 🎉 🎉 

I'm trying to update my widget every 30 min, but the UPDATE event that should be emitted after 30 min (using updatePeriodMillis config) never happens. I used the DebugEventsWidgets from the example project but I had the same problem, this event never be logged

I use an Android simulator to test it, Could it be the problem?
Should I test on a real device? 

Thanks!

**Comment by sAleksovski** [comment] 2023-11-14 20:30
Can you share your widgetprovider xml file?
Or relevant app config if using expo?

I just tried with the expo example in the repo, and it works even after killing the app.
I had to add updatePeriodMillis in https://github.com/sAleksovski/react-native-android-widget/blob/master/example-expo/app.config.ts since it was missing, and rebuild the apk. I'll update the example soon.

Keep in mind that Android decided when to update the widget, and it will not be exactly the amount you specified.

![Screenshot_20231114_211856_Nova7.jpg](https://github.com/sAleksovski/react-native-android-widget/assets/7473800/c88973a8-b5b8-4c66-b1d2-9292b1c4ba49)

**Comment by Facundo1609** [comment] 2023-11-14 20:35
Thanks for the answer! I'm not using expo. This is the .xml of the widget

<img width="724" alt="Screenshot 2023-11-14 at 17 32 13" src="https://github.com/sAleksovski/react-native-android-widget/assets/84348170/1c7a4255-747b-4954-8da7-0d28418b7e32">

Is there something missing? 

I waited for 1 hour just in case, but nothing happened

**Comment by sAleksovski** [comment] 2023-11-14 20:38
Can you share the widget and widgetTaskHandler?

**Comment by Facundo1609** [comment] 2023-11-20 16:33
Actually, I'm trying to catch the automatic WIDGET_UPDATE event using the example app without Expo. I pulled the last changes today and I'm running the app from `react-native-android-widget/example`, and I'm testing the DebugEventsWidgets widget. 

DebugEventsWidgets logs other events like WIDGET_RESIZDE, but after 30 min (approx), the automatic WIDGET_UPDATE  is not logged. Should it work even if I'm not using Expo? 

<img width="332" alt="Screenshot 2023-11-20 at 13 32 17" src="https://github.com/sAleksovski/react-native-android-widget/assets/84348170/f37c811f-5077-47e8-9739-6736299cbe24">

**Comment by sAleksovski** [comment] 2023-11-22 17:28
![image](https://github.com/sAleksovski/react-native-android-widget/assets/7473800/39e4a65f-8009-4b03-a897-0ccff6b8388d)

**Comment by Facundo1609** [comment] 2023-11-22 18:07
Using `/example` right? Maybe it is a problem with my simulator

**Comment by sAleksovski** [comment] 2023-11-22 18:40
Yes, starting with `npm run android && npm run start`

When it didn't print anything after 30 minutes, I just focused the emulator and opened the app drawer. The event was fired after a few seconds.

**Comment by sAleksovski** [comment] 2023-11-29 18:25
Did you make any progress here?
I opened the emulator again today and had a few more `WIDGET_UPDATE` events

**Comment by Facundo1609** [comment] 2023-11-30 15:25
I resolved the problem using `react-native-background-fetch` to update the widget every hour

**Comment by sAleksovski** [comment] 2023-11-30 16:32
I'm glad you found a workaround.

I'll close this issue since I could not reproduce it.

**Closed by sAleksovski** 2023-11-30 16:32 UTC

**Comment by outaTiME** [comment] 2024-05-07 22:55
I'm in the same boat, I can't get the widget to update automatically, I'm using Expo 50 and I have the update threshold set to 30 minutes (just like the example).
I have a call to a service before the widget update maybe that is what is causing the issue?
I leave here some code along with the plugin definition in the `app.config`:

```
// app.config.js

[
  'react-native-android-widget',
  {
    fonts: ['./assets/fonts/FiraGO-Regular-Minimal.otf'],
    widgets: [
      {
        name: 'Rate',
        // https://developer.android.com/guide/practices/ui_guidelines/widget_design?hl=es-419
        // 70 * n − 30 (2x2)
        minWidth: '110dp',
        minHeight: '110dp',
        label: 'Cotizaciones',
        description:
          'Mantenete al tanto de las cotizaciones durante el transcurso del día.',
        previewImage: './assets/widgets/android-2x2.png',
        resizeMode: 'none',
        widgetFeatures: 'reconfigurable|configuration_optional',
        // https://saleksovski.github.io/react-native-android-widget/docs/public-api/interfaces/Widget#updateperiodmillis
        updatePeriodMillis: 30 * 60 * 1000,
      },
    ],
  },
]

// task handler

const nameToWidget = {
  Rate: RateWidget,
};

const getRateValue = (value, type) => {
  // use value from single changes
  const buy = Array.isArray(value) ? value[0] : value;
  const sell = Array.isArray(value) ? value[1] : value;
  if (type === 'buy') {
    return buy;
  } else if (type === 'average') {
    return (buy + sell) / 2;
  }
  return sell;
};

const getWidgetProps = async (widgetInfo) => {
  // TODO: handle widget types
  const storageKey = `${widgetInfo.widgetName}:${widgetInfo.widgetId}:config`;
  const config = await AsyncStorage.getItem(storageKey)
    .then((value) => JSON.parse(value ?? '{}'))
    .catch(console.warn);
  const rateTypes = AmbitoDolar.getAvailableRateTypes();
  const type = config?.rate ?? rateTypes[0];
  // TODO: export fetch uri to env
  const rates = await Helper.getJson('https://api.ambito-dolar.app/fetch');
  /* const [timestamp, value, change] = [
    '2024-04-25T15:45:24-03:00',
    [1010, 1040],
    0,
    1040,
    1040,
    '3ac8a499f49d9a2bb52b212720659168',
  ]; */
  // const [timestamp, value, change] = [];
  const [timestamp, value, change] = rates[type];
  console.log('>>> getWidgetProps', storageKey, config, type);
  return {
    size: widgetInfo?.width,
    type,
    change,
    value: getRateValue(value, config?.value),
    timestamp,
  };
};

export async function taskHandler(props) {
  console.log('>>> widgetTaskHandler', props);
  const widgetInfo = props.widgetInfo;
  const Widget = nameToWidget[widgetInfo.widgetName];
  switch (props.widgetAction) {
    case 'WIDGET_ADDED':
    case 'WIDGET_UPDATE':
    case 'WIDGET_RESIZED': {
      const widgetProps = await getWidgetProps(widgetInfo);
      console.log('>>> widgetTaskHandler (render)', widgetProps);
      props.renderWidget(<Widget {...widgetProps} />);
      break;
    }
    case 'WIDGET_DELETED':
      // Not needed for now
      break;
    case 'WIDGET_CLICK':
      // Not needed for now
      break;
    default:
      break;
  }
}
```

I hope it is useful 🙏

**Comment by sAleksovski** [comment] 2024-05-08 06:48
Create a minimal example app with a widget that reproduces the issue and I can take a look.

**Comment by outaTiME** [comment] 2024-06-30 21:15
After a long time here, I'm back to widgets in android and already with version 51 of Expo.

Throughout this time, I was testing on different physical phones and I found a recurring behavior in each of them.

The first time a widget is added to the home screen it updates for a short period and then stops updating, but if I reboot the phone it starts updating recurrently and within the configured interval.

(This behavior even occurs between different versions of Android).

I hope this comment is useful to reach a solution without having to implement the alternative solution of @Facundo1609 (which generates a lot of dirt in the code).

At the time, I built an MRE, but I didn't share it, it was super simple, it obtained a date remotely and displayed it in the center of the widget and the same behavior mentioned above occurred.

**Comment by sAleksovski** [comment] 2024-06-30 21:29
> The first time a widget is added to the home screen **it updates for a short period** and then stops updating

What is a "short period"? 1 hour, 1 day?

> it obtained a date remotely and displayed it in the center of the widget

What do you mean be "remotely"?

I think an example app would still be beneficial, as well as some logs you get when it stops updating.

**Comment by outaTiME** [comment] 2024-06-30 21:37
> What is a "short period"? 1 hour, 1 day?

I don't have a specific time, it might just update once and stop doing it.

> What do you mean be "remotely"?

I call an external service (e.g. https://worldtimeapi.org/api/ip) inside `WIDGET_UPDATE` of the `taskHandler`.

```js
export async function taskHandler(props) {
  const widgetInfo = props.widgetInfo;
  const Widget = nameToWidget[widgetInfo.widgetName];
  switch (props.widgetAction) {
    case 'WIDGET_ADDED':
    case 'WIDGET_UPDATE':
      await fetch('https://worldtimeapi.org/api/ip')
        .then((response) => response.json())
        .then(({ utc_datetime: datetime } = {}) => {
          console.log('>>> taskHandler (renderWidget)', widgetInfo, datetime);
          props.renderWidget(
            <Widget
              {...{
                size: widgetInfo?.width,
                datetime,
              }}
            />,
          );
        })
        .catch((e) => {
          console.warn(e);
          // trace and ignore render
        });
      break;
    default:
      break;
  }
}
```
