### ISSUE TITLE
widget ui does not render on android 12 

### ISSUE THREAD

**Issue by moeinrahimi** [sAleksovski/react-native-android-widget#59] opened 2023-12-25 13:06 UTC
hi my widget works fine on android 14, but on android 13 there is no rendered ui but when you touch the applications starts, it looks like the functionality is there but not ui itself.

**Comment by moeinrahimi** [comment] 2023-12-25 13:06
also my widget sends an http request could that be related?

**Comment by sAleksovski** [comment] 2023-12-25 13:31
I can't tell from your description.

Can you try without the http request?
Can you share some logs?
Can you share your widget and widgetTaskHandler? (Or even better, a minimal example widget that reproduces the issue)

**Comment by linhnt29** [comment] 2023-12-27 02:41
I'm using Android 12 and when add widget to homepage, it displayed nothing. 
Debug via Android Studio I got an error " java.lang.IllegalArgumentException: width and height must be > 0"
Metro service got message that widgetInfo width & height = 0.
Worked fine on Android 13

**Comment by sAleksovski** [comment] 2023-12-27 17:07
Looks like some view is too small.
It probably is not related to Android version, but to the phone/emulator screen size.
Some view cannot be shown because the widget is too small.

Try deleting parts of the widget and you will see which part causes the error.

Also,
Can you try without the http request?
Can you share some logs?
Can you share your widget and widgetTaskHandler? (Or even better, a minimal example widget that reproduces the issue)

**Comment by sAleksovski** [comment] 2024-01-10 17:55
I'm closing this since there is no way to reproduce it.

Feel free to reopen it with an example widget and steps to reproduce.

**Closed by sAleksovski** 2024-01-10 17:55 UTC
