### ISSUE TITLE
listing data displays with api call 

### ISSUE THREAD

**Issue by abrar0123** [sAleksovski/react-native-android-widget#94] opened 2024-06-26 13:31 UTC
i want to displays listing with api data in react native but not be able , how to displays api  data listing

**Comment by sAleksovski** [comment] 2024-06-26 13:53
Define "not able".

What have you tried?

Please provide a minimal app reproducing the issue.

**Comment by abrar0123** [comment] 2024-06-27 00:36
1-in react native widget now displays list static data in widgets 
2- i want to display the dynamic list data by api calls , api call is correct and also receive data but issue is that not apply logic of
react like usestate , useeffects , here is screenshots
i was use in here : 
![image](https://github.com/sAleksovski/react-native-android-widget/assets/104258004/a30b4763-e23d-4e0a-8d70-309548c3954b)
 and get error here : 
![image](https://github.com/sAleksovski/react-native-android-widget/assets/104258004/2cfd7cd5-c7e7-4ab3-93c1-4fc271f1a1a9)
so i try to get di this with another method and  i am able to call api data and get list data but when i am when i want to  displays my list nothing will displays on when i add widget 

@sAleksovski please look and give me solution

**Comment by sAleksovski** [comment] 2024-06-27 04:45
Please read the docs.

https://saleksovski.github.io/react-native-android-widget/docs/tutorial/widget-design

One of the first things there is that you cannot use hooks inside the widget. 

Fetch the data outside the widget in the `widget-task-handler` and pass it to the widget as a prop.

**Comment by abrar0123** [comment] 2024-06-29 04:07
okey i understane but still one problem i get that it takes so much time to load widget with static or dynamic list mapping due so how manage this . 
@sAleksovski

**Comment by sAleksovski** [comment] 2024-06-29 05:59
I guess the speed depends on the number of items, how much it takes to get the data from server, what kind of device you have...

The list widget from the example app is loading fairly quickly. 

I'll close this issue since the last question is not related with the original issue.

**Closed by sAleksovski** 2024-06-29 05:59 UTC
