### ISSUE TITLE
widgets didnot displays on google devices

### ISSUE THREAD

**Issue by abrar0123** [sAleksovski/react-native-android-widget#95] opened 2024-07-04 09:35 UTC
why that widgets even not displays on gooogle devices , i test on multiple devices as well as emultors but in widgets options not shows on my app even remaing devices successfullly displays

**Comment by sAleksovski** [comment] 2024-07-04 09:56
I don't understand. Where is it not displaying? 

Can you share a video? 

Widget picker or when you add it to home screen?

**Comment by abrar0123** [comment] 2024-07-06 00:11
yes means in widget picker where we pick all other apps widget didnot show that widget

**Comment by sAleksovski** [comment] 2024-07-06 05:39
Please try whether the widgets from the example app from releases page are shown.

https://github.com/sAleksovski/react-native-android-widget/releases

Also, share your apk file, or create a small example project that does not work on Google device, but works on others.

**Comment by sAleksovski** [comment] 2024-07-22 20:55
@abrar0123 do you still have this issue, or you figured it out?

**Comment by sAleksovski** [comment] 2024-07-30 21:59
I'm closing this since I cannot reproduce it, and there is not enough information. 

Feel free to reopen it when you provide a recording of the sample app running in Google device.

**Closed by sAleksovski** 2024-07-30 21:59 UTC

**Comment by vincemavill** [comment] 2024-08-12 02:32
![55](https://github.com/user-attachments/assets/af9b480f-0f0e-4c23-ae68-24ff62b57b94)
i encounter the issue non expo react native

**Comment by sAleksovski** [comment] 2024-08-12 05:26
@vincemavill this is not related, @abrar0123 said the widgets were not shown in the widget picker. 

For your case check the logs and you will find the error.

**Comment by vincemavill** [comment] 2024-08-12 08:05
@sAleksovski no logs error showing,

**Comment by sAleksovski** [comment] 2024-08-12 15:23
There must be something in the log. 

If there is nothing in the react native log, check the adb log.
